### PR TITLE
feat: add year to iteration picker

### LINKED ISSUE #237: Compute iteration dates and expose them to UI
For the dropdown in #235, and in other iteration-related views, we might want to show years in iteration date strings. Between 67 and 120, we cover several years.

### PR DESCRIPTION
**Pull request by rjfc**
Closes #237.

### CODE REVIEW

**Comment by rjfc** [comment]
Does this format look odd?
image

**Comment by aminomancer** [comment]
hmm. what percent of items do you think wrap onto 2 lines?

**Comment by aminomancer** [comment]
and no actually it looks pretty good IMO.

maybe we should make the sidebar wider. I've noticed many meta bug titles get cut off. and it's not like we need the space in the main body. can you just change that in this bug? making the sidebar wider should automatically make the iteration picker wider.

**Comment by aminomancer** [comment]
see what's the smallest width you can make the sidebar so that none of the route labels get cut off

**Comment by rjfc** [comment]
> hmm. what percent of items do you think wrap onto 2 lines?

Before increasing the sidebar width, about 50%.

> see what's the smallest width you can make the sidebar so that none of the NavLinks get cut off

Done:
image

**Review by aminomancer — APPROVED** [review]

**Pull request merged**
