### PR TITLE
feat: add an iteration picker

### LINKED ISSUE #232: Add an iteration picker
We support paths like `https://www.bugzy.org/iteration/:id`, but aside from the current and next iteration, the only way to access arbitrary iterations is by manually entering the path. We could add a <select> iteration picker in the navigation sidebar.

### PR DESCRIPTION
**Pull request by aminomancer**
Fixes #232

### CODE REVIEW

**Comment by aminomancer** [comment]
image

with dark reader:
image

**Comment by aminomancer** [comment]
The searchbox and select dropdown menu

image

**Comment by aminomancer** [comment]
I also tested it out with dates. Dates are definitely very useful, the only reason I'm uncertain about it is that they make the strings long enough to overflow. So in the <select>, the string gets truncated with an ellipsis, and in the dropdown, the <option>'s may wrap onto 2 lines.

image

**Comment by aminomancer** [comment]
Could also switch to a numeric date format. It seems less legible though, and I have heard americans are more used to m/d/y, canadians more used to y/m/d, and everyone else uses d/m/y (or something like that).

**Review by nuggetsnegin — APPROVED** [review]
Tested and LGTM!

I don't find the truncation bad and agree having dates in that format as most legible. I think the only nitpick is the line break when the iteration string is too long when the menu is opened causing inconsistencies. But I don't think there's a good solution for this without hurting legibility (and it only seems to be a case with the EOY and current iteration).

image

**Comment by aminomancer** [comment]
Yeahhh... it's a bit ugly having them wrap. Do you think showing the year is worthwhile? If it was the only thing wrapping I'd be inclined to get rid of the year display. But since the (current) wraps too, there wouldn't be much benefit. But maybe there's something else we can do instead of ` (current)`, like a star or something more concise. Any thoughts?

**Comment by nuggetsnegin** [comment]
> Yeahhh... it's a bit ugly having them wrap. Do you think showing the year is worthwhile? If it was the only thing wrapping I'd be inclined to get rid of the year display. But since the (current) wraps too, there wouldn't be much benefit. But maybe there's something else we can do instead of ` (current)`, like a star or something more concise. Any thoughts?

Yeah I'm not sure if the year is worthwhile, I think it's obvious enough from the iteration # what year it should be. I like the idea of a star, just thinking out loud some other options could maybe be bolding the current iteration or an underline? I'm curious how the star would look tho, if it fits nicely that's probably most ideal.

**Comment by aminomancer** [comment]
⁕
★
🟊
✦
✶
some unicode options

**Comment by aminomancer** [comment]
Oh you know what... if we don't put (current) in the label, then you won't be able to search it up by typing `current`, which I think is a relatively useful feature. So I guess I'll just get rid of the years but not the (current) part.

**Pull request merged**
